### ISSUE TITLE
Infinite Zero Tracking Issue

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/ProdigyMathGameHacking#104]
- [X] Make a reliable server for Infinite Zero
- [X] Get HTTPS for the Zero Server
- [x] Implement Infinite Zero into PHEx
- [x] Release PHEx 2.2.0 on GitHub
- [x] Update all instances of P-NP to match 2.2.0
- [x] @afkvido  Update the Mozilla webstore version
- [x] @afkvido Leave a note in statusmessage.json
- [x] @afkvido Update the Edge webstore version
- [x] @Erisfiregamer1 Update pnpb.erisws.com

**Comment by afkvido** [comment]
Doing `Implement Infinite Zero into PHEx` right now.

**Comment by Erisfiregamer1** [comment]
Clicking buttons is my passion

**Comment by afkvido** [comment]
Hell yea

**Comment by afkvido** [comment]
Time to release PHEx 2.2.0, Here goes nothing!

**Comment by afkvido** [comment]
HELL YEA

**Comment by afkvido** [comment]
I've submittted the new version to the Edge Web Store

**Comment by afkvido** [comment]
Ayyy, we got in on the Mozilla web store, though i dont think PHEx works on firefox

**Comment by Erisfiregamer1** [comment]
I'll test it in a bit.
Also, to vido:
I gave you the Panel credentials, just grab the Github repo .zip, upload it to the server from File Manager, hit the 3 dots on the side and unzip.

**Comment by Erisfiregamer1** [comment]
I'll do it this time though...

**Comment by afkvido** [comment]
bet
