### ISSUE TITLE
PHEx 3.1.0 Tracking Issue

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/ProdigyMathGameHacking#170]
- [ ] Internationalize PHEx ([All languages](https://developer.chrome.com/docs/webstore/i18n/))
- [x] PHEx: Remove custom backgrounds
- [x] Switch to pnpm, it's wayyy better than npm.
- [ ] Make the extension popup.html look a bit nicer by using CSS

**Comment by afkvido** [comment]
All conversation can be held at:
- #178
