### ISSUE TITLE
!!! PHEx MV3 tracking issue

### ISSUE THREAD

**Issue by Erisfiregamer1** [ProdigyPNP/ProdigyMathGameHacking#79]
### Describe your issue

This is where we're going to track the progress of the MV3 migration.
- Service workers have to replace background pages.
- [x] **Do they work?**
- Network request modification is now handled with the new declarativeNetRequest API, so migrate the modification to that
- [x] **Does it work?**
- Remotely-hosted code is no longer allowed to be executed (nope, didnt even affect us), so continue to load it from P-NP
- [ ] ***Does it work?***
- Some changes were made in MV3 including one that broke no-csp, figure out what's causing it and bypass (maybe ProdigyX could help)
- [x] **Do the changes work?**

### Date of submittion

6/15/2022

**Comment by afkvido** [comment]
>  Remotely-hosted code is no longer allowed to be executed; so get the game.min.js from the extension libraries (basically, P-NP becomes useless)

No. We will fight to the fucking death. P-NP will not become useless.

**Comment by donaldli2020** [comment]
or we can do a cheat menu without redirecting the code

**Comment by donaldli2020** [comment]
oops i did ctrl shift enter not ctrl enter

**Comment by afkvido** [comment]
> or we can do a cheat menu without redirecting the code

That would only work for some hacks, examples:

Set Gold
Toggle Membership
Pause Game


Those are essentially one-line hacks, and can be accessed through `Boot.something.iForgot`.

**Comment by Erisfiregamer1** [comment]
I honestly believe with the state of this org that MV3 won't be done.

**Comment by afkvido** [comment]
I think its the state of you

**Comment by Erisfiregamer1** [comment]
I take what I said back.

**Comment by afkvido** [comment]
Same- i also deleted my comment

**Comment by afkvido** [comment]
We need to get this on MV3 or no chrome web store

**Comment by Erisfiregamer1** [comment]
Well, that's an issue.

**Comment by afkvido** [comment]
YAAAAAA
